
TARGET_BOARD_PLATFORM := hamoa
QCOM_BOARD_PLATFORMS += hamoa
TARGET_NO_BOOTLOADER := true

#TODO see if the below two are really needed.
BUILD_BROKEN_MISSING_REQUIRED_MODULES  := true
ALLOW_MISSING_DEPENDENCIES := true
FORCE_USE_ANDROIDMK_FOR_WPA_CONF := true

TARGET_HAS_GENERIC_KERNEL_HEADERS := true

TARGET_NO_RPC := true
PRODUCT_VENDOR_MOVE_ENABLED := true
PRODUCT_ENABLE_DUMPSTATE_SUPPORT := false

BOARD_AVB_ENABLE := true

$(call inherit-product, device/qcom/hamoa/common64.mk)

TARGET_USES_AL := true

TARGET_FWK_SUPPORTS_FULL_VALUEADDS := false

# Set SoC manufacturer property
PRODUCT_PROPERTY_OVERRIDES += \
     ro.soc.manufacturer=QTI

ifneq ($(TARGET_FWK_SUPPORTS_FULL_VALUEADDS), true)
 $(call soong_config_set, qti_fwk_valueadds, fwk_supports_full_valueadds, disabled)
endif

TARGET_USES_QMAA := true
TARGET_USES_QMAA_RECOMMENDED_BOOT_CONFIG := false
TARGET_USES_QMAA_OVERRIDE_QSEECOMD_LISTENERS := true
TARGET_USES_QMAA_OVERRIDE_DISPLAY := false
TARGET_USES_QMAA_OVERRIDE_AUDIO   := false
TARGET_USES_QMAA_OVERRIDE_VIDEO   := false
TARGET_USES_QMAA_OVERRIDE_CAMERA  := false
TARGET_USES_QMAA_OVERRIDE_GFX     := false
TARGET_USES_QMAA_OVERRIDE_WFD     := false
TARGET_USES_QMAA_OVERRIDE_GPS     := false
TARGET_USES_QMAA_OVERRIDE_ANDROID_CORE := false
TARGET_USES_QMAA_OVERRIDE_WLAN    := true
TARGET_USES_QMAA_OVERRIDE_BLUETOOTH   := true
TARGET_USES_QMAA_OVERRIDE_FM  := false
TARGET_USES_QMAA_OVERRIDE_BLUETOOTH_AUDIO := false
TARGET_USES_QMAA_OVERRIDE_CVP  := false
TARGET_USES_QMAA_OVERRIDE_SV  := false
TARGET_USES_QMAA_OVERRIDE_FASTCV  := false
TARGET_USES_QMAA_OVERRIDE_SCVE  := false
TARGET_USES_QMAA_OVERRIDE_DATA := false
TARGET_USES_QMAA_OVERRIDE_DATA_NET := false
TARGET_USES_QMAA_OVERRIDE_DATA_CONNECTIVITY := false
TARGET_USES_QMAA_OVERRIDE_RIL_DATA := false
TARGET_USES_QMAA_OVERRIDE_DATA_IPA_AGENT := false
TARGET_USES_QMAA_OVERRIDE_MSM_BUS_MODULE := false
TARGET_USES_QMAA_OVERRIDE_DRM    := false
TARGET_USES_QMAA_OVERRIDE_KMGK := false
TARGET_USES_QMAA_OVERRIDE_MSMIRQBALANCE := false
TARGET_USES_QMAA_OVERRIDE_VPP := false
TARGET_USES_QMAA_OVERRIDE_GP := false
TARGET_USES_QMAA_OVERRIDE_PERF := false
TARGET_USES_QMAA_OVERRIDE_SENSORS := false
TARGET_USES_QMAA_OVERRIDE_SYNX := false
TARGET_USES_QMAA_OVERRIDE_SECUREMSM_TESTS := true
TARGET_USES_QMAA_OVERRIDE_SMCINVOKE := true
TARGET_USES_QMAA_OVERRIDE_SOTER := false
TARGET_USES_QMAA_OVERRIDE_REMOTE_EFS := false
TARGET_USES_QMAA_OVERRIDE_USB := false
TARGET_USES_QMAA_OVERRIDE_DPM := false
TARGET_USES_QMAA_OVERRIDE_FASTRPC := false
TARGET_USES_QMAA_OVERRIDE_SPU := false
TARGET_USES_QMAA_OVERRIDE_UWB := false
TARGET_USES_QMAA_OVERRIDE_SST_CLIENTS := false
TARGET_USES_QMAA_OVERRIDE_SECURITY_TESTS := false
TARGET_USES_QMAA_OVERRIDE_TIME_SERVICES := false
TARGET_USES_QMAA_OVERRIDE_VIBRATOR:= false

# Disable DLKM generation until build support is available
TARGET_KERNEL_DLKM_DISABLE := true

# Tech specific flags
TARGET_KERNEL_DLKM_AUDIO_OVERRIDE := false
TARGET_KERNEL_DLKM_BT_OVERRIDE := true
TARGET_KERNEL_DLKM_CAMERA_OVERRIDE := false
TARGET_KERNEL_DLKM_NFC_OVERRIDE := false
TARGET_KERNEL_DLKM_ESE_OVERRIDE := false
TARGET_KERNEL_DLKM_DATA_OVERRIDE := false
TARGET_KERNEL_DLKM_DISPLAY_OVERRIDE := false
TARGET_KERNEL_DLKM_MM_DRV_OVERRIDE := false
TARGET_KERNEL_DLKM_SECURE_MSM_OVERRIDE := true
TARGET_KERNEL_DLKM_SECUREMSM_QTEE_OVERRIDE := true
TARGET_KERNEL_DLKM_LIMITS_OVERRIDE := false
TARGET_KERNEL_DLKM_TOUCH_OVERRIDE := false
TARGET_KERNEL_DLKM_VIDEO_OVERRIDE := false
TARGET_KERNEL_DLKM_WLAN_OVERRIDE := true
TARGET_KERNEL_DLKM_MMRM_OVERRIDE := false
TARGET_KERNEL_DLKM_DATARMNET_OVERRIDE := false
TARGET_KERNEL_DLKM_DATARMNETEXT_OVERRIDE := false
TARGET_KERNEL_DLKM_SYNX_OVERRIDE := false
TARGET_KERNEL_DLKM_DATAIPA_OVERRIDE := false
TARGET_KERNEL_DLKM_FASTRPC_OVERRIDE := false
TARGET_KERNEL_DLKM_EVA_OVERRIDE := false
TARGET_KERNEL_DLKM_SPU_OVERRIDE := false
TARGET_KERNEL_DLKM_FINGERPRINT_OVERRIDE := false

ifeq ($(TARGET_USES_QMAA), true)
    ifneq ($(TARGET_USES_QMAA_OVERRIDE_PERF), true)
        TARGET_DISABLE_PERF_OPTIMIZATIONS := true
    else
        TARGET_DISABLE_PERF_OPTIMIZATIONS := false
    endif
else
    TARGET_DISABLE_PERF_OPTIMIZATIONS := false
endif

ifneq ("$(wildcard device/qcom/$(TARGET_BOARD_PLATFORM)-kernel/vendor_dlkm/system_dlkm.modules.blocklist)", "")
PRODUCT_COPY_FILES += device/qcom/$(TARGET_BOARD_PLATFORM)-kernel/vendor_dlkm/system_dlkm.modules.blocklist:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/system_dlkm.modules.blocklist
endif

# QRTR related packages
PRODUCT_PACKAGES += qrtr-lookup
PRODUCT_PACKAGES += libqrtr

# diag-router
TARGET_HAS_DIAG_ROUTER := true

# Set kernel version
TARGET_KERNEL_VERSION := 6.12

#----------------------------------------------------------------------
# wlan specific
#----------------------------------------------------------------------
ifeq ($(TARGET_USES_QMAA), true)
    ifneq ($(TARGET_USES_QMAA_OVERRIDE_WLAN), true)
        include device/qcom/wlan/default/wlan.mk
    else
        include device/qcom/wlan/hamoa/wlan.mk
    endif
else
     include device/qcom/wlan/hamoa/wlan.mk
endif

$(foreach vdefs, $(sort $(wildcard vendor/qcom/defs/product-defs/system/*.mk)), \
    $(call inherit-product, $(vdefs)))

$(foreach vdefs, $(sort $(wildcard vendor/qcom/defs/product-defs/vendor/*.mk)), \
    $(call inherit-product, $(vdefs)))
